### ISSUE TITLE
Fix Selenium click error (on Ubuntu 22.04)

### ISSUE THREAD

**Issue by theoden-dd** [Roxe322/prpr#2]
There were errors for lots of more or less recent homeworks.

The download part crashed with an error like:

```sh
Traceback (most recent call last):
  File "{$HOME}/.pyenv/versions/3.9.10/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "{$HOME}/.pyenv/versions/3.9.10/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "*/prpr/prpr/main.py", line 213, in <module>
    main()
  File "*/prpr/prpr/main.py", line 160, in main
    for results, homework in zip(
  File "*/prpr/prpr/download.py", line 88, in download_batch
    urls = _get_zip_urls(driver, homework.revisor_url)
  File "*/prpr/prpr/download.py", line 209, in _get_zip_urls
    element.click()
  File "{$HOME}/.pyenv/versions/3.9.10/envs/yapr-prpr/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "{$HOME}/.pyenv/versions/3.9.10/envs/yapr-prpr/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "{$HOME}/.pyenv/versions/3.9.10/envs/yapr-prpr/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "{$HOME}/.pyenv/versions/3.9.10/envs/yapr-prpr/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)

selenium.common.exceptions.ElementClickInterceptedException: Message: Element <article class="tab__text"> is not clickable at point (811,266) because another element <div class="skills-modal skills-modal_align_center skills-modal_theme_transparent expanded-image expanded-image_align_center expanded-image_theme_transparent"> obscures it
```

I'll attach couple of examples of {homework_number}.{iteration} {cohort} to make possible some suggestions on the content version on the platform.
See also the thread in Pachca (limited access): https://app.pachca.com/chats?thread_id=1086996

OS: Ubuntu 22.04

**Comment by theoden-dd** [comment]
The earliest fail I met on the 19.05.2023.

Here are some of the earliest examples:

25.05: 7.2 на 60 когорте 

```sh
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <article class="tab__text"> is not clickable at point (811,266) because another element <div class="skills-modal skills-modal_align_center skills-modal_theme_transparent expanded-image expanded-image_align_center expanded-image_theme_transparent"> obscures it
```

7.1 61

```sh
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <article class="tab__text"> is not clickable at point (811,266) because another element <div class="skills-modal skills-modal_align_center skills-modal_theme_transparent expanded-image expanded-image_align_center expanded-image_theme_transparent"> obscures it
```

13.1 51

```sh
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <article class="tab__text"> is not clickable at point (811,266) because another element <div class="skills-modal skills-modal_align_center skills-modal_theme_transparent expanded-image expanded-image_align_center expanded-image_theme_transparent"> obscures it
```

26.05: 10.2 57 - success

**Comment by theoden-dd** [comment]
And the latest examples include:

21.06: 12.2 57 success

23.06: 1.3 69

```sh
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <article class="tab__text"> is not clickable at point (811,266) because another element <div class="skills-modal skills-modal_align_center skills-modal_theme_transparent expanded-image expanded-image_align_center expanded-image_theme_transparent"> obscures it
```

12.3 19+

```sh
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <article class="tab__text"> is not clickable at point (811,266) because another element <div class="skills-modal skills-modal_align_center skills-modal_theme_transparent expanded-image expanded-image_align_center expanded-image_theme_transparent"> obscures it
```
